/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AgendaDao;
import dao.FuncionarioDao;
import entities.Agenda;
import entities.Funcionario;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import lombok.extern.log4j.Log4j2;
import org.hibernate.SessionFactory;
import utils.HibernateUtil;
import utils.ReportsGenerator;
import utils.VisualsConfig;

@Log4j2
public class DlgAgenda extends javax.swing.JDialog {

    private Optional<Funcionario> funcionario;

    private final SessionFactory sessionFactory;
    private List<Agenda> agendasSemFiltroLista;
    private List<Agenda> agendasComFiltroLista;
    private Agenda agenda;
    private AgendaDao agendaDao;
    private int idAgenda;
    private int idFunc;
    private boolean isAdmin;

    /**
     * Creates new form DlgAgenda
     */
    public DlgAgenda(java.awt.Frame parent, boolean modal, boolean isAdmin, Funcionario func) {
        super(parent, modal);
        initComponents();

        this.sessionFactory = HibernateUtil.getSessionFactory();

        VisualsConfig.setPropsToWindow(this, "Agenda", parent);

        this.idAgenda = 0;
        this.idFunc = 0;
        this.agenda = new Agenda();
        this.agendaDao = new AgendaDao(sessionFactory);
        this.agendasComFiltroLista = new ArrayList<>();
        this.isAdmin = isAdmin;

        if (!isAdmin) {
            this.funcionario = Optional.of(func);

            btnBuscarFunc.setEnabled(false);
            txfID.setText(String.valueOf(funcionario.get().getId()));
            txfNome.setText(funcionario.get().getNome());
            txfAtividade.setText(funcionario.get().getAtividade());

            String permissao = func.getPermissao().getDescricao();
            this.agendasSemFiltroLista = agendaDao.buscarPorPermissao(permissao);

            agendasSemFiltroLista = agendasSemFiltroLista.stream().filter(
                    registro -> registro.getFuncionario().getId() == funcionario.get().getId())
                    .collect(Collectors.toList());
        } else {
            this.agendasSemFiltroLista = agendaDao.buscarTodos();
            this.funcionario = Optional.empty();
        }

        limparAgenda();

        LocalDate dataAtual = LocalDate.now();
        ftfDataAgendaCriar.setText(dataAtual.getDayOfMonth() + "/"
                + dataAtual.getMonthValue() + "/"
                + dataAtual.getYear());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txfAtividade = new javax.swing.JTextField();
        txfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarFunc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txfID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ftfDataAgendaFiltro = new javax.swing.JFormattedTextField();
        btnFiltrarAgenda = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        pnlCadastroAgenda = new javax.swing.JPanel();
        btnCriarAgenda = new javax.swing.JButton();
        ftfDataAgendaCriar = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftfHoraIniAgenda = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        ftfHoraFimAgenda = new javax.swing.JFormattedTextField();
        btnEditar = new javax.swing.JButton();
        btnNovoAtend = new javax.swing.JButton();
        btnGerarRelatorio = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Início", "Fim"
            }
        ));
        jScrollPane1.setViewportView(tblAgenda);
        if (tblAgenda.getColumnModel().getColumnCount() > 0) {
            tblAgenda.getColumnModel().getColumn(0).setMinWidth(50);
            tblAgenda.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblAgenda.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionário"));

        txfAtividade.setEditable(false);

        txfNome.setEditable(false);

        jLabel3.setText("Nome:");

        jLabel7.setText("Atividade:");

        btnBuscarFunc.setText("Buscar Funcionário");
        btnBuscarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFuncActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        txfID.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfNome)
                    .addComponent(txfAtividade)
                    .addComponent(btnBuscarFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(txfID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jLabel8.setText("Filtrar por data:");

        try {
            ftfDataAgendaFiltro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnFiltrarAgenda.setText("Filtrar");
        btnFiltrarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarAgendaAgendaActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        pnlCadastroAgenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova agenda"));

        btnCriarAgenda.setText("Criar");
        btnCriarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarAgendaAgendaActionPerformed(evt);
            }
        });

        try {
            ftfDataAgendaCriar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Data:");

        jLabel5.setText("Horário início:");

        try {
            ftfHoraIniAgenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Horário fim:");

        try {
            ftfHoraFimAgenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnlCadastroAgendaLayout = new javax.swing.GroupLayout(pnlCadastroAgenda);
        pnlCadastroAgenda.setLayout(pnlCadastroAgendaLayout);
        pnlCadastroAgendaLayout.setHorizontalGroup(
            pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroAgendaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCriarAgenda)
                    .addGroup(pnlCadastroAgendaLayout.createSequentialGroup()
                        .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftfDataAgendaCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(ftfHoraIniAgenda)
                            .addComponent(ftfHoraFimAgenda))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnlCadastroAgendaLayout.setVerticalGroup(
            pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroAgendaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfDataAgendaCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftfHoraIniAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftfHoraFimAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCriarAgenda)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNovoAtend.setText("Criar/ver atendimentos");
        btnNovoAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAtendActionPerformed(evt);
            }
        });

        btnGerarRelatorio.setText("Gerar Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(837, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlCadastroAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(ftfDataAgendaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFiltrarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNovoAtend)
                                    .addGap(43, 43, 43)
                                    .addComponent(btnGerarRelatorio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(23, 23, 23)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(497, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ftfDataAgendaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(btnFiltrarAgenda))
                            .addGap(18, 18, 18)
                            .addComponent(btnLimpar)
                            .addGap(46, 46, 46)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEditar)
                                .addComponent(btnNovoAtend)
                                .addComponent(btnGerarRelatorio))
                            .addGap(50, 50, 50))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pnlCadastroAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparAgenda() {
        if (isAdmin) {
            txfID.setText("");
            txfNome.setText("");
            txfAtividade.setText("");
            this.funcionario = Optional.empty();
        }

        this.idAgenda = 0;
        this.idFunc = 0;
        this.agenda = new Agenda();
        LocalDate dataAtual = LocalDate.now();
        ftfDataAgendaCriar.setText(dataAtual.getDayOfMonth() + "/"
                + dataAtual.getMonthValue() + "/"
                + dataAtual.getYear());
        ftfHoraIniAgenda.setText("");
        ftfHoraFimAgenda.setText("");
        ftfDataAgendaFiltro.setText("");

        this.agendasSemFiltroLista = agendaDao.buscarTodos();

        atualizarTabelaAgenda(agendasSemFiltroLista);
    }

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            String idString = String.valueOf(tblAgenda.getValueAt(tblAgenda.getSelectedRow(), 0));
            idAgenda = Integer.parseInt(idString);
            Optional<Agenda> agenda0 = agendaDao.buscar(idAgenda);
            this.agenda = agenda0.get();

            if (isAdmin) {
                idString = String.valueOf(tblAgenda.getValueAt(tblAgenda.getSelectedRow(), 4));
                int funcId = Integer.parseInt(idString);
                funcionario = new FuncionarioDao(sessionFactory).buscar(funcId);
                txfID.setText(String.valueOf(funcionario.get().getId()));
                txfNome.setText(funcionario.get().getNome());
                txfAtividade.setText(funcionario.get().getAtividade());
            }

            String[] dataArray = agenda.getData().toString().split("-");

            ftfDataAgendaCriar.setText(dataArray[2] + "/" + dataArray[1] + "/" + dataArray[0]);
            ftfHoraIniAgenda.setText(String.valueOf(agenda.getHorario_inicio()));
            ftfHoraFimAgenda.setText(String.valueOf(agenda.getHorario_final()));

        } catch (Exception e) {
            log.error("Erro ao selecionar na tabela agenda: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao selecionar na tabela agenda.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCriarAgendaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarAgendaAgendaActionPerformed
        try {
            if (funcionario.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione um funcionário.");
                return;
            }

            if (ftfDataAgendaCriar.getText().equals("  /  /    ")) {
                JOptionPane.showMessageDialog(null, "Preencha o campo data.");
                return;
            }

            if (ftfHoraIniAgenda.getText().equals("  :  ") || ftfHoraFimAgenda.getText().equals("  :  ")) {
                JOptionPane.showMessageDialog(null, "Preencha o horário de início e o horário final da agenda!");
                return;
            }

            // data nova agenda
            String dataString = ftfDataAgendaCriar.getText();
            String[] dataArray = dataString.split("/");
            LocalDate dataParse = LocalDate.of(
                    Integer.parseInt(dataArray[2]),
                    Integer.parseInt(dataArray[1]),
                    Integer.parseInt(dataArray[0])
            );

            // hora inicio nova agenda
            String horaIniString = ftfHoraIniAgenda.getText();
            String[] horaIniArray = horaIniString.split(":");
            LocalTime horaIniParse = LocalTime.of(
                    Integer.parseInt(horaIniArray[0]),
                    Integer.parseInt(horaIniArray[1])
            );

            // hora final nova agenda
            String horaFimString = ftfHoraFimAgenda.getText();
            String[] horaFimArray = horaFimString.split(":");
            LocalTime horaFimParse = LocalTime.of(
                    Integer.parseInt(horaFimArray[0]),
                    Integer.parseInt(horaFimArray[1])
            );

            if (horaIniParse.isAfter(horaFimParse)) {
                JOptionPane.showMessageDialog(null, "O horário inicial deve ser menor que o horário final!");
                return;
            }

            boolean agendaExiste = false;
            if (idAgenda == 0) {
                for (Agenda agd : agendasSemFiltroLista) {
                    if (agd.getData().equals(dataParse)
                            && agd.getHorario_final().equals(horaFimParse)
                            && agd.getHorario_inicio().equals(horaIniParse)
                            && agd.getFuncionario().getId() == funcionario.get().getId()) {
                        agendaExiste = true;
                    }
                }
            }

            if (agendaExiste) {
                JOptionPane.showMessageDialog(null, "Esta agenda já existe para o funcionário selecionado."
                        + "\nAltere a data e/ou os horários informados!");
                return;
            }

            idAgenda = agenda.getId();
            agenda.setFuncionario(funcionario.get());
            agenda.setData(dataParse);
            agenda.setHorario_inicio(horaIniParse);
            agenda.setHorario_final(horaFimParse);
            agenda.setStatus("ativo");

            Optional<Agenda> agenda0 = Optional.empty();

            if (idAgenda == 0) {
                agenda0 = agendaDao.salvar(agenda);
                agendasSemFiltroLista.add(agenda);
            } else {
                agenda0 = agendaDao.atualizar(agenda);
            }

            if (agenda0.isPresent()) {
                if (idAgenda == 0) {
                    JOptionPane.showMessageDialog(null, "Agenda cadastrada com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Agenda atualizada com sucesso!");
                }
            }

            this.limparAgenda();
        } catch (Exception e) {
            log.error("Erro ao cadastrar agenda: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar agenda.");
        }
    }//GEN-LAST:event_btnCriarAgendaAgendaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.limparAgenda();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFiltrarAgendaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarAgendaAgendaActionPerformed
        try {
            agendasComFiltroLista = agendasSemFiltroLista;

            String dataString = ftfDataAgendaFiltro.getText();

            if (!dataString.equals("  /  /    ")) {
                String[] dataArray = dataString.split("/");
                LocalDate dataAud = LocalDate.of(Integer.parseInt(dataArray[2]),
                        Integer.parseInt(dataArray[1]),
                        Integer.parseInt(dataArray[0]));
                agendasComFiltroLista = agendasComFiltroLista.stream()
                        .filter(registro -> registro.getData().equals(dataAud)).collect(Collectors.toList());
            }

            if (isAdmin && funcionario.isPresent()) {
                agendasComFiltroLista = agendasComFiltroLista.stream().filter(
                        registro -> registro.getFuncionario().getId() == funcionario.get().getId())
                        .collect(Collectors.toList());
            }

            if (agendasComFiltroLista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhum registro encontrado!");
            } else {
                atualizarTabelaAgenda(agendasComFiltroLista);
            }
        } catch (Exception e) {
            log.error("Erro ao buscar na tabela de auditoria: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar na tabela de auditoria: " + e.getMessage());
        }
    }//GEN-LAST:event_btnFiltrarAgendaAgendaActionPerformed

    private void btnBuscarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFuncActionPerformed
        DlgBuscaFuncionario buscaFuncionario = new DlgBuscaFuncionario(null, true, sessionFactory);
        buscaFuncionario.setVisible(true);

        funcionario = new FuncionarioDao(sessionFactory).buscar(buscaFuncionario.id);
        if (funcionario.isPresent()) {
            txfID.setText(String.valueOf(funcionario.get().getId()));
            txfNome.setText(funcionario.get().getNome());
            txfAtividade.setText(funcionario.get().getAtividade());
            this.idFunc = funcionario.get().getId();
        }
    }//GEN-LAST:event_btnBuscarFuncActionPerformed

    private void btnNovoAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAtendActionPerformed

        String idString = String.valueOf(tblAgenda.getValueAt(tblAgenda.getSelectedRow(), 0));
        idAgenda = Integer.parseInt(idString);
        Optional<Agenda> agenda0 = agendaDao.buscar(idAgenda);
        this.agenda = agenda0.get();

        if (agenda0.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione uma agenda para ver seus atendimentos.");
            return;
        }

        DlgAtendimento dlgAtendimento = new DlgAtendimento(null, true, agenda);
        dlgAtendimento.setVisible(true);
    }//GEN-LAST:event_btnNovoAtendActionPerformed

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        String dataAgenda = ftfDataAgendaFiltro.getText();

        Map params = new HashMap();
        params.put("dataAgenda", dataAgenda);
        new ReportsGenerator().gerarRelatorioRobusto("/reports/relatorio_agenda_data.jrxml", params);
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    public void atualizarTabelaAgenda(List<Agenda> lista) {
        try {
            if (isAdmin) {
                Object[] cabecalho = {"ID", "Data", "Começa", "Termina", "FuncID"};
                Object[][] dadosTabela = new Object[lista.size()][5];
                if (lista.size() > 0) {
                    for (int i = 0; i < lista.size(); i++) {
                        dadosTabela[i][0] = lista.get(i).getId();
                        dadosTabela[i][1] = lista.get(i).getData();
                        dadosTabela[i][2] = lista.get(i).getHorario_inicio();
                        dadosTabela[i][3] = lista.get(i).getHorario_final();
                        dadosTabela[i][4] = lista.get(i).getFuncionario().getId();
                    }
                }

                tblAgenda.setModel(new DefaultTableModel(dadosTabela, cabecalho) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }

                });
            } else {
                Object[] cabecalho = {"ID", "Data", "Começa", "Termina"};
                Object[][] dadosTabela = new Object[lista.size()][4];
                if (lista.size() > 0) {
                    for (int i = 0; i < lista.size(); i++) {
                        dadosTabela[i][0] = lista.get(i).getId();
                        dadosTabela[i][1] = lista.get(i).getData();
                        dadosTabela[i][2] = lista.get(i).getHorario_inicio();
                        dadosTabela[i][3] = lista.get(i).getHorario_final();
                    }
                }

                tblAgenda.setModel(new DefaultTableModel(dadosTabela, cabecalho) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }

                });
            }

            tblAgenda.setSelectionMode(0);

            // redimensiona as colunas de uma tabela
            TableColumn column = null;
            for (int i = 0; i < tblAgenda.getColumnCount(); i++) {
                column = tblAgenda.getColumnModel().getColumn(i);
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                column.setCellRenderer(centerRenderer);
            }

            column = tblAgenda.getColumnModel().getColumn(0);
            column.setPreferredWidth(50);
            column.setMaxWidth(50);
            column.setMinWidth(50);
        } catch (Exception e) {
            log.error("Erro ao buscar na tabela de agendas: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar na tabela de agendas: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAgenda dialog = new DlgAgenda(new javax.swing.JFrame(), true, false, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFunc;
    private javax.swing.JButton btnCriarAgenda;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltrarAgenda;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovoAtend;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField ftfDataAgendaCriar;
    private javax.swing.JFormattedTextField ftfDataAgendaFiltro;
    private javax.swing.JFormattedTextField ftfHoraFimAgenda;
    private javax.swing.JFormattedTextField ftfHoraIniAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCadastroAgenda;
    private javax.swing.JTable tblAgenda;
    private javax.swing.JTextField txfAtividade;
    private javax.swing.JTextField txfID;
    private javax.swing.JTextField txfNome;
    // End of variables declaration//GEN-END:variables
}
