/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AgendaDao;
import dao.AtendimentoDao;
import dao.FuncionarioDao;
import entities.Agenda;
import entities.Atendimento;
import entities.Funcionario;
import entities.Pet;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import lombok.extern.log4j.Log4j2;
import org.hibernate.SessionFactory;
import utils.HibernateUtil;
import utils.VisualsConfig;

@Log4j2
public class DlgAgenda extends javax.swing.JDialog {

    private Optional<Funcionario> funcionario;
    private Optional<Pet> pet;
    private final SessionFactory sessionFactory;
    private List<Agenda> agendasSemFiltroLista;
    private List<Agenda> agendasComFiltroLista;
    private List<Atendimento> atendimentosSemFiltroLista;
    private List<Atendimento> atendimentosComFiltroLista;
    private Agenda agenda;
    private AgendaDao agendaDao;
    private Atendimento atendimento;
    private AtendimentoDao atendimentoDao;
    private int idAgenda;
    private int idAtendimento;
    private int idFunc;
    private boolean isAdmin;

    /**
     * Creates new form DlgAgenda
     */
    public DlgAgenda(java.awt.Frame parent, boolean modal, boolean isAdmin, Funcionario func) {
        super(parent, modal);
        initComponents();

        this.sessionFactory = HibernateUtil.getSessionFactory();

        VisualsConfig.setPropsToWindow(this, "Agenda", parent);

        this.idAgenda = 0;
        this.idAtendimento = 0;
        this.idFunc = 0;
        this.agenda = new Agenda();
        this.agendaDao = new AgendaDao(sessionFactory);
        this.agendasComFiltroLista = new ArrayList<>();
        this.isAdmin = isAdmin;
        
        this.pet = Optional.empty();

        if (!isAdmin) {
            this.funcionario = Optional.of(func);

            btnBuscarFunc.setEnabled(false);
            txfID.setText(String.valueOf(funcionario.get().getId()));
            txfNome.setText(funcionario.get().getNome());
            txfAtividade.setText(funcionario.get().getAtividade());

            String permissao = func.getPermissao().getDescricao();
            if (permissao.equals("petshop")) {
//                tbpAgenda.setEnabledAt(2, false);
                this.agendasSemFiltroLista = agendaDao.buscarPorPermissao(permissao);
            } else {
//                tbpAgenda.setEnabledAt(1, false);
                this.agendasSemFiltroLista = agendaDao.buscarPorPermissao(permissao);
            }

            agendasSemFiltroLista = agendasSemFiltroLista.stream().filter(
                    registro -> registro.getFuncionario().getId() == funcionario.get().getId())
                    .collect(Collectors.toList());
        } else {
            this.agendasSemFiltroLista = agendaDao.buscarTodos();
            this.funcionario = Optional.empty();
        }

        atualizarTabelaAgenda(agendasSemFiltroLista);

        LocalDate dataAtual = LocalDate.now();
        ftfDataAgendaCriar.setText(dataAtual.getDayOfMonth() + "/"
                + dataAtual.getMonthValue() + "/"
                + dataAtual.getYear());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        tbpAgenda = new javax.swing.JTabbedPane();
        pnlAgenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txfAtividade = new javax.swing.JTextField();
        txfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarFunc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txfID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ftfDataAgendaFiltro = new javax.swing.JFormattedTextField();
        btnFiltrarAgenda = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        pnlCadastroAgenda = new javax.swing.JPanel();
        btnCriarAgenda = new javax.swing.JButton();
        ftfDataAgendaCriar = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftfHoraIniAgenda = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        ftfHoraFimAgenda = new javax.swing.JFormattedTextField();
        btnEditarAgenda = new javax.swing.JButton();
        btnNovoAtend = new javax.swing.JButton();
        pnlAtendimento = new javax.swing.JPanel();
        pnlCadastroAtend = new javax.swing.JPanel();
        btnCriarAtendimento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxHorario = new javax.swing.JComboBox<>();
        ftfDataAtendCriar = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBuscarPetAtend = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        pnlBuscaAtend = new javax.swing.JPanel();
        btnEditarAtend = new javax.swing.JButton();
        btnExcluirAtend = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnFiltrarAtendimento = new javax.swing.JButton();
        ftfDataBusca = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDataAtualAtend = new javax.swing.JButton();
        btnVerInfos = new javax.swing.JButton();
        btnLimparAtend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Início", "Fim"
            }
        ));
        jScrollPane1.setViewportView(tblAgenda);
        if (tblAgenda.getColumnModel().getColumnCount() > 0) {
            tblAgenda.getColumnModel().getColumn(0).setMinWidth(50);
            tblAgenda.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblAgenda.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionário"));

        txfAtividade.setEditable(false);

        txfNome.setEditable(false);

        jLabel3.setText("Nome:");

        jLabel7.setText("Atividade:");

        btnBuscarFunc.setText("Buscar Funcionário");
        btnBuscarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFuncActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        txfID.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfNome)
                    .addComponent(txfAtividade)
                    .addComponent(btnBuscarFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(txfID))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jLabel8.setText("Filtrar por data:");

        try {
            ftfDataAgendaFiltro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnFiltrarAgenda.setText("Filtrar");
        btnFiltrarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarAgendaAgendaActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        pnlCadastroAgenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova agenda"));

        btnCriarAgenda.setText("Criar");
        btnCriarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarAgendaAgendaActionPerformed(evt);
            }
        });

        try {
            ftfDataAgendaCriar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Data:");

        jLabel5.setText("Horário início:");

        try {
            ftfHoraIniAgenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Horário fim:");

        try {
            ftfHoraFimAgenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnlCadastroAgendaLayout = new javax.swing.GroupLayout(pnlCadastroAgenda);
        pnlCadastroAgenda.setLayout(pnlCadastroAgendaLayout);
        pnlCadastroAgendaLayout.setHorizontalGroup(
            pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroAgendaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCriarAgenda)
                    .addGroup(pnlCadastroAgendaLayout.createSequentialGroup()
                        .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftfDataAgendaCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(ftfHoraIniAgenda)
                            .addComponent(ftfHoraFimAgenda))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnlCadastroAgendaLayout.setVerticalGroup(
            pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroAgendaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfDataAgendaCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftfHoraIniAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftfHoraFimAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCriarAgenda)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnEditarAgenda.setText("Editar");
        btnEditarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAgendaActionPerformed(evt);
            }
        });

        btnNovoAtend.setText("Novo atendimento");
        btnNovoAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAtendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgendaLayout = new javax.swing.GroupLayout(pnlAgenda);
        pnlAgenda.setLayout(pnlAgendaLayout);
        pnlAgendaLayout.setHorizontalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCadastroAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgendaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(ftfDataAgendaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(208, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAgendaLayout.createSequentialGroup()
                                .addComponent(btnNovoAtend)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditarAgenda))
                            .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendaLayout.createSequentialGroup()
                                    .addComponent(btnLimpar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnFiltrarAgenda))))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        pnlAgendaLayout.setVerticalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAgendaLayout.createSequentialGroup()
                        .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfDataAgendaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(46, 46, 46)
                        .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFiltrarAgenda)
                            .addComponent(btnLimpar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarAgenda)
                            .addComponent(btnNovoAtend))
                        .addGap(50, 50, 50))
                    .addGroup(pnlAgendaLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlCadastroAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        tbpAgenda.addTab("Agenda", pnlAgenda);

        pnlCadastroAtend.setBorder(javax.swing.BorderFactory.createTitledBorder("Novo Atendimento"));

        btnCriarAtendimento.setText("Criar");
        btnCriarAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarAtendimentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Horário:");

        jLabel9.setText("Data:");

        cbxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        try {
            ftfDataAtendCriar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Pet:");

        btnBuscarPetAtend.setText("Buscar pet");
        btnBuscarPetAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPetAtendActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        javax.swing.GroupLayout pnlCadastroAtendLayout = new javax.swing.GroupLayout(pnlCadastroAtend);
        pnlCadastroAtend.setLayout(pnlCadastroAtendLayout);
        pnlCadastroAtendLayout.setHorizontalGroup(
            pnlCadastroAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroAtendLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCriarAtendimento)
                .addGap(41, 41, 41))
            .addGroup(pnlCadastroAtendLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(pnlCadastroAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ftfDataAtendCriar)
                    .addComponent(btnBuscarPetAtend, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        pnlCadastroAtendLayout.setVerticalGroup(
            pnlCadastroAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroAtendLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlCadastroAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ftfDataAtendCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarPetAtend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCriarAtendimento)
                .addGap(18, 18, 18))
        );

        pnlBuscaAtend.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Atendimentos"));

        btnEditarAtend.setText("Editar");

        btnExcluirAtend.setText("Excluir");

        jLabel11.setText("Filtrar por data:");

        btnFiltrarAtendimento.setText("Filtrar");

        try {
            ftfDataBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jScrollPane2.setPreferredSize(new java.awt.Dimension(250, 250));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Horário", "Data", "Pet ID"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnDataAtualAtend.setText("Data atual");
        btnDataAtualAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataAtualAtendAtendActionPerformed(evt);
            }
        });

        btnVerInfos.setText("Ver infos");

        btnLimparAtend.setText("Limpar");
        btnLimparAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparAtendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscaAtendLayout = new javax.swing.GroupLayout(pnlBuscaAtend);
        pnlBuscaAtend.setLayout(pnlBuscaAtendLayout);
        pnlBuscaAtendLayout.setHorizontalGroup(
            pnlBuscaAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscaAtendLayout.createSequentialGroup()
                .addGroup(pnlBuscaAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscaAtendLayout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(pnlBuscaAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlBuscaAtendLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(ftfDataBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFiltrarAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscaAtendLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBuscaAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscaAtendLayout.createSequentialGroup()
                                .addComponent(btnVerInfos)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarAtend)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluirAtend))
                            .addComponent(btnDataAtualAtend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimparAtend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );
        pnlBuscaAtendLayout.setVerticalGroup(
            pnlBuscaAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscaAtendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscaAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnFiltrarAtendimento)
                    .addComponent(ftfDataBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDataAtualAtend)
                .addGap(18, 18, 18)
                .addComponent(btnLimparAtend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBuscaAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarAtend)
                    .addComponent(btnExcluirAtend)
                    .addComponent(btnVerInfos))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout pnlAtendimentoLayout = new javax.swing.GroupLayout(pnlAtendimento);
        pnlAtendimento.setLayout(pnlAtendimentoLayout);
        pnlAtendimentoLayout.setHorizontalGroup(
            pnlAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtendimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastroAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBuscaAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        pnlAtendimentoLayout.setVerticalGroup(
            pnlAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtendimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBuscaAtend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCadastroAtend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbpAgenda.addTab("Atendimento", pnlAtendimento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(837, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tbpAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(551, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tbpAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 61, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparAgenda() {
        if (isAdmin) {
            txfID.setText("");
            txfNome.setText("");
            txfAtividade.setText("");
            this.funcionario = Optional.empty();
        }

        this.idAgenda = 0;
        this.idAtendimento = 0;
        this.idFunc = 0;
        this.agenda = new Agenda();
        LocalDate dataAtual = LocalDate.now();
        ftfDataAgendaCriar.setText(dataAtual.getDayOfMonth() + "/"
                + dataAtual.getMonthValue() + "/"
                + dataAtual.getYear());
        ftfHoraIniAgenda.setText("");
        ftfHoraFimAgenda.setText("");
        ftfDataAgendaFiltro.setText("");

        this.agendasSemFiltroLista = agendaDao.buscarTodos();

        atualizarTabelaAgenda(agendasSemFiltroLista);
    }

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLimparAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparAtendActionPerformed

    private void btnDataAtualAtendAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataAtualAtendAtendActionPerformed

    }//GEN-LAST:event_btnDataAtualAtendAtendActionPerformed

    private void btnBuscarPetAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPetAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPetAtendActionPerformed

    private void btnCriarAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarAtendimentoActionPerformed

    private void btnEditarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAgendaActionPerformed
        try {
            String idString = String.valueOf(tblAgenda.getValueAt(tblAgenda.getSelectedRow(), 0));
            idAgenda = Integer.parseInt(idString);
            Optional<Agenda> agenda0 = agendaDao.buscar(idAgenda);
            this.agenda = agenda0.get();

            if (isAdmin) {
                idString = String.valueOf(tblAgenda.getValueAt(tblAgenda.getSelectedRow(), 4));
                int funcId = Integer.parseInt(idString);
                funcionario = new FuncionarioDao(sessionFactory).buscar(funcId);
                txfID.setText(String.valueOf(funcionario.get().getId()));
                txfNome.setText(funcionario.get().getNome());
                txfAtividade.setText(funcionario.get().getAtividade());
            }

            String[] dataArray = agenda.getData().toString().split("-");

            ftfDataAgendaCriar.setText(dataArray[2] + "/" + dataArray[1] + "/" + dataArray[0]);
            ftfHoraIniAgenda.setText(String.valueOf(agenda.getHorario_inicio()));
            ftfHoraFimAgenda.setText(String.valueOf(agenda.getHorario_final()));

        } catch (Exception e) {
            log.error("Erro ao selecionar na tabela agenda: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao selecionar na tabela agenda.");
        }
    }//GEN-LAST:event_btnEditarAgendaActionPerformed

    private void btnCriarAgendaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarAgendaAgendaActionPerformed
        try {
            if (funcionario.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione um funcionário.");
                return;
            }

            if (ftfDataAgendaCriar.getText().equals("  /  /    ")) {
                JOptionPane.showMessageDialog(null, "Preencha o campo data.");
                return;
            }

            if (ftfHoraIniAgenda.getText().equals("  :  ") || ftfHoraFimAgenda.getText().equals("  :  ")) {
                JOptionPane.showMessageDialog(null, "Preencha o horário de início e o horário final da agenda!");
                return;
            }

            // data nova agenda
            String dataString = ftfDataAgendaCriar.getText();
            String[] dataArray = dataString.split("/");
            LocalDate dataParse = LocalDate.of(
                    Integer.parseInt(dataArray[2]),
                    Integer.parseInt(dataArray[1]),
                    Integer.parseInt(dataArray[0])
            );

            // hora inicio nova agenda
            String horaIniString = ftfHoraIniAgenda.getText();
            String[] horaIniArray = horaIniString.split(":");
            LocalTime horaIniParse = LocalTime.of(
                    Integer.parseInt(horaIniArray[0]),
                    Integer.parseInt(horaIniArray[1])
            );

            // hora final nova agenda
            String horaFimString = ftfHoraFimAgenda.getText();
            String[] horaFimArray = horaFimString.split(":");
            LocalTime horaFimParse = LocalTime.of(
                    Integer.parseInt(horaFimArray[0]),
                    Integer.parseInt(horaFimArray[1])
            );

            if (horaIniParse.isAfter(horaFimParse)) {
                JOptionPane.showMessageDialog(null, "O horário inicial deve ser menor que o horário final!");
                return;
            }

            boolean agendaExiste = false;
            if (idAgenda == 0) {
                for (Agenda agd : agendasSemFiltroLista) {
                    if (agd.getData().equals(dataParse)
                            && agd.getHorario_final().equals(horaFimParse)
                            && agd.getHorario_inicio().equals(horaIniParse)
                            && agd.getFuncionario().getId() == funcionario.get().getId()) {
                        agendaExiste = true;
                    }
                }
            }

            if (agendaExiste) {
                JOptionPane.showMessageDialog(null, "Esta agenda já existe para o funcionário selecionado."
                        + "\nAltere a data e/ou os horários informados!");
                return;
            }

            idAgenda = agenda.getId();
            agenda.setFuncionario(funcionario.get());
            agenda.setData(dataParse);
            agenda.setHorario_inicio(horaIniParse);
            agenda.setHorario_final(horaFimParse);
            agenda.setStatus("ativo");

            Optional<Agenda> agenda0 = Optional.empty();

            if (idAgenda == 0) {
                agenda0 = agendaDao.salvar(agenda);
                agendasSemFiltroLista.add(agenda);
            } else {
                agenda0 = agendaDao.atualizar(agenda);
            }

            if (agenda0.isPresent()) {
                if (idAgenda == 0) {
                    JOptionPane.showMessageDialog(null, "Agenda cadastrada com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Agenda atualizada com sucesso!");
                }
            }

            this.limparAgenda();
        } catch (Exception e) {
            log.error("Erro ao cadastrar agenda: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar agenda.");
        }
    }//GEN-LAST:event_btnCriarAgendaAgendaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.limparAgenda();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFiltrarAgendaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarAgendaAgendaActionPerformed
        try {
            agendasComFiltroLista = agendasSemFiltroLista;

            String dataString = ftfDataAgendaFiltro.getText();

            if (!dataString.equals("  /  /    ")) {
                String[] dataArray = dataString.split("/");
                LocalDate dataAud = LocalDate.of(Integer.parseInt(dataArray[2]),
                        Integer.parseInt(dataArray[1]),
                        Integer.parseInt(dataArray[0]));
                agendasComFiltroLista = agendasComFiltroLista.stream()
                        .filter(registro -> registro.getData().equals(dataAud)).collect(Collectors.toList());
            }

            if (isAdmin && funcionario.isPresent()) {
                agendasComFiltroLista = agendasComFiltroLista.stream().filter(
                        registro -> registro.getFuncionario().getId() == funcionario.get().getId())
                        .collect(Collectors.toList());
            }

            if (agendasComFiltroLista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhum registro encontrado!");
            } else {
                atualizarTabelaAgenda(agendasComFiltroLista);
            }
        } catch (Exception e) {
            log.error("Erro ao buscar na tabela de auditoria: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar na tabela de auditoria: " + e.getMessage());
        }
    }//GEN-LAST:event_btnFiltrarAgendaAgendaActionPerformed

    private void btnBuscarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFuncActionPerformed
        DlgBuscaFuncionario buscaFuncionario = new DlgBuscaFuncionario(null, true, sessionFactory);
        buscaFuncionario.setVisible(true);

        funcionario = new FuncionarioDao(sessionFactory).buscar(buscaFuncionario.id);
        if (funcionario.isPresent()) {
            txfID.setText(String.valueOf(funcionario.get().getId()));
            txfNome.setText(funcionario.get().getNome());
            txfAtividade.setText(funcionario.get().getAtividade());
            this.idFunc = funcionario.get().getId();
        }
    }//GEN-LAST:event_btnBuscarFuncActionPerformed

    private void btnNovoAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAtendActionPerformed
        try {
            String idString = String.valueOf(tblAgenda.getValueAt(tblAgenda.getSelectedRow(), 0));
            idAgenda = Integer.parseInt(idString);
            Optional<Agenda> agenda0 = agendaDao.buscar(idAgenda);
            this.agenda = agenda0.get();
            
            // colocar os horarios da agenda selecionada fracionado de 10 em 10 mins
            String[] dataArray = agenda.getData().toString().split("-");

            ftfDataAtendCriar.setText(dataArray[2] + "/" + dataArray[1] + "/" + dataArray[0]);            

            tbpAgenda.setSelectedIndex(1);


        } catch (Exception e) {
            log.error("Erro ao selecionar na tabela agenda: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao selecionar na tabela agenda.");
        }
    }//GEN-LAST:event_btnNovoAtendActionPerformed

    public void atualizarTabelaAgenda(List<Agenda> lista) {
        try {
            if (isAdmin) {
                Object[] cabecalho = {"ID", "Data", "Começa", "Termina", "FuncID"};
                Object[][] dadosTabela = new Object[lista.size()][5];
                if (lista.size() > 0) {
                    for (int i = 0; i < lista.size(); i++) {
                        dadosTabela[i][0] = lista.get(i).getId();
                        dadosTabela[i][1] = lista.get(i).getData();
                        dadosTabela[i][2] = lista.get(i).getHorario_inicio();
                        dadosTabela[i][3] = lista.get(i).getHorario_final();
                        dadosTabela[i][4] = lista.get(i).getFuncionario().getId();
                    }
                }

                tblAgenda.setModel(new DefaultTableModel(dadosTabela, cabecalho) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }

                });
            } else {
                Object[] cabecalho = {"ID", "Data", "Começa", "Termina"};
                Object[][] dadosTabela = new Object[lista.size()][4];
                if (lista.size() > 0) {
                    for (int i = 0; i < lista.size(); i++) {
                        dadosTabela[i][0] = lista.get(i).getId();
                        dadosTabela[i][1] = lista.get(i).getData();
                        dadosTabela[i][2] = lista.get(i).getHorario_inicio();
                        dadosTabela[i][3] = lista.get(i).getHorario_final();
                    }
                }

                tblAgenda.setModel(new DefaultTableModel(dadosTabela, cabecalho) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }

                });
            }

            tblAgenda.setSelectionMode(0);

            // redimensiona as colunas de uma tabela
            TableColumn column = null;
            for (int i = 0; i < tblAgenda.getColumnCount(); i++) {
                column = tblAgenda.getColumnModel().getColumn(i);
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                column.setCellRenderer(centerRenderer);
            }

            column = tblAgenda.getColumnModel().getColumn(0);
            column.setPreferredWidth(50);
            column.setMaxWidth(50);
            column.setMinWidth(50);
        } catch (Exception e) {
            log.error("Erro ao buscar na tabela de auditoria: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar na tabela de auditoria: " + e.getMessage());
        }
    }

    public void atualizarTabelaAtendimento(List<Atendimento> lista) {
//        try {
//            if (isAdmin) {
//                Object[] cabecalho = {"ID", "Data", "Começa", "Termina", "FuncID"};
//                Object[][] dadosTabela = new Object[lista.size()][5];
//                if (lista.size() > 0) {
//                    for (int i = 0; i < lista.size(); i++) {
//                        dadosTabela[i][0] = lista.get(i).getId();
//                        dadosTabela[i][1] = lista.get(i).getData();
//                        dadosTabela[i][2] = lista.get(i).getHorario_inicio();
//                        dadosTabela[i][3] = lista.get(i).getHorario_final();
//                        dadosTabela[i][4] = lista.get(i).getFuncionario().getId();
//                    }
//                }
//
//                tblAgenda.setModel(new DefaultTableModel(dadosTabela, cabecalho) {
//                    @Override
//                    public boolean isCellEditable(int row, int column) {
//                        return false;
//                    }
//
//                });
//            } else {
//                Object[] cabecalho = {"ID", "Data", "Começa", "Termina"};
//                Object[][] dadosTabela = new Object[lista.size()][4];
//                if (lista.size() > 0) {
//                    for (int i = 0; i < lista.size(); i++) {
//                        dadosTabela[i][0] = lista.get(i).getId();
//                        dadosTabela[i][1] = lista.get(i).getData();
//                        dadosTabela[i][2] = lista.get(i).getHorario_inicio();
//                        dadosTabela[i][3] = lista.get(i).getHorario_final();
//                    }
//                }
//
//                tblAgenda.setModel(new DefaultTableModel(dadosTabela, cabecalho) {
//                    @Override
//                    public boolean isCellEditable(int row, int column) {
//                        return false;
//                    }
//
//                });
//            }
//
//            tblAgenda.setSelectionMode(0);
//
//            // redimensiona as colunas de uma tabela
//            TableColumn column = null;
//            for (int i = 0; i < tblAgenda.getColumnCount(); i++) {
//                column = tblAgenda.getColumnModel().getColumn(i);
//                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
//                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
//                column.setCellRenderer(centerRenderer);
//            }
//
//            column = tblAgenda.getColumnModel().getColumn(0);
//            column.setPreferredWidth(50);
//            column.setMaxWidth(50);
//            column.setMinWidth(50);
//        } catch (Exception e) {
//            log.error("Erro ao buscar na tabela de auditoria: " + e.getMessage());
//            JOptionPane.showMessageDialog(null, "Erro ao buscar na tabela de auditoria: " + e.getMessage());
//        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAgenda dialog = new DlgAgenda(new javax.swing.JFrame(), true, false, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFunc;
    private javax.swing.JButton btnBuscarPetAtend;
    private javax.swing.JButton btnCriarAgenda;
    private javax.swing.JButton btnCriarAtendimento;
    private javax.swing.JButton btnDataAtualAtend;
    private javax.swing.JButton btnEditarAgenda;
    private javax.swing.JButton btnEditarAtend;
    private javax.swing.JButton btnExcluirAtend;
    private javax.swing.JButton btnFiltrarAgenda;
    private javax.swing.JButton btnFiltrarAtendimento;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimparAtend;
    private javax.swing.JButton btnNovoAtend;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVerInfos;
    private javax.swing.JComboBox<String> cbxHorario;
    private javax.swing.JFormattedTextField ftfDataAgendaCriar;
    private javax.swing.JFormattedTextField ftfDataAgendaFiltro;
    private javax.swing.JFormattedTextField ftfDataAtendCriar;
    private javax.swing.JFormattedTextField ftfDataBusca;
    private javax.swing.JFormattedTextField ftfHoraFimAgenda;
    private javax.swing.JFormattedTextField ftfHoraIniAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlAgenda;
    private javax.swing.JPanel pnlAtendimento;
    private javax.swing.JPanel pnlBuscaAtend;
    private javax.swing.JPanel pnlCadastroAgenda;
    private javax.swing.JPanel pnlCadastroAtend;
    private javax.swing.JTable tblAgenda;
    private javax.swing.JTabbedPane tbpAgenda;
    private javax.swing.JTextField txfAtividade;
    private javax.swing.JTextField txfID;
    private javax.swing.JTextField txfNome;
    // End of variables declaration//GEN-END:variables
}
