/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PetDao;
import entities.Pet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import lombok.extern.log4j.Log4j2;
import org.hibernate.SessionFactory;
import utils.HibernateUtil;
import utils.ReportsGenerator;
import utils.VisualsConfig;

@Log4j2
public class DlgBuscaPet extends javax.swing.JDialog {

    private final SessionFactory sessionFactory;
    private PetDao petDAO;
    private List<Pet> pets;
    int id = 0;
    boolean relatorio = false;

    /**
     * Creates new form DlgBuscaAutor
     */
    public DlgBuscaPet(java.awt.Frame parent, boolean modal, SessionFactory sf) {
        super(parent, modal);
        initComponents();
        btnSelecionar.setText("Selecionar");
        VisualsConfig.setPropsToWindow(this, "Selecionar Pet", parent);
        this.sessionFactory = HibernateUtil.getSessionFactory();
        petDAO = new PetDao(sessionFactory);
    }

    public DlgBuscaPet(java.awt.Frame parent, boolean modal, SessionFactory sf, boolean relatorio) {
        super(parent, modal);
        initComponents();
        this.relatorio = relatorio;
        btnSelecionar.setText("Gerar");
        VisualsConfig.setPropsToWindow(this, "Selecionar Pet", parent);
        this.sessionFactory = HibernateUtil.getSessionFactory();
        petDAO = new PetDao(sessionFactory);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfBusca = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPet = new javax.swing.JTable();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Procure o pet que deseja, clique na linha correspondente da tabela e aperte o botão \"Selecionar\".");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblPet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Nome", "Raça", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPet.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblPet);
        if (tblPet.getColumnModel().getColumnCount() > 0) {
            tblPet.getColumnModel().getColumn(0).setMinWidth(70);
            tblPet.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblPet.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pet", "Cliente", "Raça" }));

        jLabel1.setText("Tipo");

        jLabel4.setText("Campo de busca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelecionar)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfBusca)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSelecionar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarDadosTabela() {
        try {
            String busca = txfBusca.getText();

            Object[] cabecalho = {"Cód.", "Nome", "Raça", "Cliente"};
            Object[][] dadosTabela = new Object[0][4];

            switch (cbxTipo.getSelectedIndex()) {
                case 0: {
                    pets = petDAO.buscarPorNome(busca);

                    dadosTabela = new Object[pets.size()][4];
                    if (pets.size() > 0) {
                        for (int i = 0; i < pets.size(); i++) {
                            dadosTabela[i][0] = pets.get(i).getId();
                            dadosTabela[i][1] = pets.get(i).getNome();
                            dadosTabela[i][2] = pets.get(i).getRaca().getNome();
                            dadosTabela[i][3] = pets.get(i).getCliente().getNome();
                        }
                    }
                    break;
                }

//                case 1: {
//                    funcionarios = funcDAO.buscarPorNomeEPermissao(busca, "admin");
//
//                    dadosTabela = new Object[funcionarios.size()][3];
//                    if (funcionarios.size() > 0) {
//                        for (int i = 0; i < funcionarios.size(); i++) {
//                            dadosTabela[i][0] = funcionarios.get(i).getId();
//                            dadosTabela[i][1] = funcionarios.get(i).getNome();
//                            dadosTabela[i][2] = funcionarios.get(i).getPermissao().getDescricao();
//                        }
//                    }
//                    break;
//                }
//
//                case 2: {
//                    funcionarios = funcDAO.buscarPorNomeEPermissao(busca, "vet");
//
//                    dadosTabela = new Object[funcionarios.size()][3];
//                    if (funcionarios.size() > 0) {
//                        for (int i = 0; i < funcionarios.size(); i++) {
//                            dadosTabela[i][0] = funcionarios.get(i).getId();
//                            dadosTabela[i][1] = funcionarios.get(i).getNome();
//                            dadosTabela[i][2] = funcionarios.get(i).getPermissao().getDescricao();
//                        }
//                    }
//                    break;
//                }
                default:
                    break;
            }

            tblPet.setModel(new DefaultTableModel(dadosTabela, cabecalho) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            });

            tblPet.setSelectionMode(0);

            // redimensiona as colunas de uma tabela
            TableColumn column = null;
            for (int i = 0; i < tblPet.getColumnCount(); i++) {
                column = tblPet.getColumnModel().getColumn(i);
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                column.setCellRenderer(centerRenderer);
            }

            column = tblPet.getColumnModel().getColumn(0);
            column.setPreferredWidth(50);
            column.setMaxWidth(50);
            column.setMinWidth(50);
        } catch (Exception e) {
            log.error("Erro ao buscar pet "
                    + "(combobox selected_item: "
                    + cbxTipo.getSelectedItem().toString()
                    + "): " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar pet.");
        }
    }

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        if (relatorio) {
            String idString = String.valueOf(tblPet.getValueAt(tblPet.getSelectedRow(), 0));
            id = Integer.parseInt(idString);
            
            Map params = new HashMap();
            params.put("pet_id", id);
            new ReportsGenerator().gerarRelatorioRobusto("/reports/relatorio_atendimentos_pet.jrxml", params);
            this.dispose();
        } else {
            try {
                String idString = String.valueOf(tblPet.getValueAt(tblPet.getSelectedRow(), 0));

                id = Integer.parseInt(idString);

                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nenhum pet selecionado.");
                System.out.println("Erro: " + e.toString());
            }
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        carregarDadosTabela();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgBuscaPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgBuscaPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgBuscaPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgBuscaPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgBuscaPet dialog = new DlgBuscaPet(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPet;
    private javax.swing.JTextField txfBusca;
    // End of variables declaration//GEN-END:variables
}
