/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entities.Funcionario;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import utils.VisualsConfig;

public class DlgLogs extends javax.swing.JDialog {

    private Funcionario funcionario;
    
    public DlgLogs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        VisualsConfig.setPropsToWindow(this, "Logs da aplicação", parent);

        try {
            BufferedReader in = new BufferedReader(new FileReader("logs/app.log"));
            String line = in.lines().collect(Collectors.joining(System.lineSeparator()));

            txaLogs.setText(line);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema ao carregar informações do arquivo /log/app.log");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlLogs = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaLogs = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnFiltrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txfFunc = new javax.swing.JTextField();
        btnBuscarFunc = new javax.swing.JButton();
        ftfDataIni = new javax.swing.JFormattedTextField();
        ftfDataFim = new javax.swing.JFormattedTextField();
        lblFechar = new javax.swing.JLabel();
        pnlAuditoria = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pnlLogs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaLogs.setEditable(false);
        txaLogs.setColumns(20);
        txaLogs.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        txaLogs.setRows(5);
        jScrollPane1.setViewportView(txaLogs);

        pnlLogs.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 274, 951, 407));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel1.setText("FILTROS");
        pnlLogs.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 78, -1, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel2.setText("Data Início:");
        pnlLogs.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 122, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel3.setText("Data Final:");
        pnlLogs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 171, 88, -1));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel4.setText("Logs do Sistema");
        pnlLogs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 19, -1, -1));
        pnlLogs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 1018, 10));

        btnFiltrar.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        pnlLogs.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 230, 78, -1));

        btnLimpar.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        pnlLogs.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel5.setText("Funcionário:");
        pnlLogs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 124, -1, -1));

        txfFunc.setEditable(false);
        txfFunc.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        txfFunc.setBorder(null);
        pnlLogs.add(txfFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 124, 294, -1));

        btnBuscarFunc.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnBuscarFunc.setText("Buscar funcionário");
        btnBuscarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFuncActionPerformed(evt);
            }
        });
        pnlLogs.add(btnBuscarFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 167, -1, -1));

        try {
            ftfDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfDataIni.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        pnlLogs.add(ftfDataIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 119, 290, -1));

        try {
            ftfDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfDataFim.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        pnlLogs.add(ftfDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 168, 290, -1));

        lblFechar.setFont(new java.awt.Font("Poppins", 1, 32)); // NOI18N
        lblFechar.setText("X");
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        pnlLogs.add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1158, 0, -1, -1));

        jTabbedPane1.addTab("Logs", pnlLogs);

        javax.swing.GroupLayout pnlAuditoriaLayout = new javax.swing.GroupLayout(pnlAuditoria);
        pnlAuditoria.setLayout(pnlAuditoriaLayout);
        pnlAuditoriaLayout.setHorizontalGroup(
            pnlAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1189, Short.MAX_VALUE)
        );
        pnlAuditoriaLayout.setVerticalGroup(
            pnlAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Auditoria", pnlAuditoria);

        btnSair.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnBuscarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFuncActionPerformed
        DlgBuscaFuncionario dlgBuscaFunc = new DlgBuscaFuncionario(null, true);
        dlgBuscaFunc.setVisible(true);
    }//GEN-LAST:event_btnBuscarFuncActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        ftfDataIni.setText("");
        ftfDataFim.setText("");
        txfFunc.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgLogs dialog = new DlgLogs(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFunc;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField ftfDataFim;
    private javax.swing.JFormattedTextField ftfDataIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JPanel pnlAuditoria;
    private javax.swing.JPanel pnlLogs;
    private javax.swing.JTextArea txaLogs;
    private javax.swing.JTextField txfFunc;
    // End of variables declaration//GEN-END:variables
}
