/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ProdutoDao;
import entities.Produto;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import lombok.extern.log4j.Log4j2;
import org.hibernate.SessionFactory;
import utils.HibernateUtil;
import utils.VisualsConfig;

@Log4j2
public class DlgProduto extends javax.swing.JDialog {

    private int id = 0;
    private Produto produto = new Produto();
    private final SessionFactory sessionFactory;

    public DlgProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.sessionFactory = HibernateUtil.getSessionFactory();

        VisualsConfig.setPropsToWindow(this, "Cadastrar produto", parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlcadastros = new javax.swing.JPanel();
        tbpCadastros = new javax.swing.JTabbedPane();
        pnlprodutos = new javax.swing.JPanel();
        txfNome = new javax.swing.JTextField();
        txfSKU = new javax.swing.JTextField();
        ftfEstoque = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDescricao = new javax.swing.JTextArea();
        ftfCusto = new javax.swing.JFormattedTextField();
        ftfVenda = new javax.swing.JFormattedTextField();
        ftfDesconto = new javax.swing.JFormattedTextField();
        cbxCategoria = new javax.swing.JComboBox<>();
        cbxStatus = new javax.swing.JComboBox<>();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        backgroundcadastro = new javax.swing.JLabel();
        pnlConsulta = new javax.swing.JPanel();
        cbxBusca = new javax.swing.JComboBox<>();
        txfBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        btnVerProduto = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlprodutos.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pnlprodutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlprodutos.add(txfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 270, 30));
        pnlprodutos.add(txfSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 270, 30));
        pnlprodutos.add(ftfEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 270, 30));

        txaDescricao.setColumns(20);
        txaDescricao.setRows(5);
        jScrollPane2.setViewportView(txaDescricao);

        pnlprodutos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 270, 110));

        ftfCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        pnlprodutos.add(ftfCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 270, 30));

        ftfVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        pnlprodutos.add(ftfVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 270, 30));

        ftfDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        pnlprodutos.add(ftfDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 270, 30));

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Alimentação", "Brinquedos", "Higiene", "Medicamentos", "Roupas" }));
        pnlprodutos.add(cbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 270, 30));

        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        pnlprodutos.add(cbxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 280, 30));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlprodutos.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 660, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlprodutos.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 660, -1, -1));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        pnlprodutos.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, -1, -1));

        backgroundcadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telacadastroproduto.png"))); // NOI18N
        pnlprodutos.add(backgroundcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbpCadastros.addTab("Produtos", null, pnlprodutos, "");

        pnlConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SKU", "Nome", "Categoria" }));
        pnlConsulta.add(cbxBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 120, 30));
        pnlConsulta.add(txfBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 560, 30));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlConsulta.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 160, 30));

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "SKU", "Nome", "Categoria", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        pnlConsulta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 880, 430));

        btnVerProduto.setText("Ver produto");
        pnlConsulta.add(btnVerProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, -1, -1));

        btnEditar.setText("Editar registro");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlConsulta.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, -1, -1));

        tbpCadastros.addTab("Busca produto", null, pnlConsulta, "");

        javax.swing.GroupLayout pnlcadastrosLayout = new javax.swing.GroupLayout(pnlcadastros);
        pnlcadastros.setLayout(pnlcadastrosLayout);
        pnlcadastrosLayout.setHorizontalGroup(
            pnlcadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpCadastros)
        );
        pnlcadastrosLayout.setVerticalGroup(
            pnlcadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpCadastros)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlcadastros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlcadastros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        id = 0;
        txfSKU.setText("");
        txfNome.setText("");
        txaDescricao.setText("");
        ftfEstoque.setText("");
        ftfCusto.setText("");
        ftfVenda.setText("");
        ftfDesconto.setText("");
        cbxStatus.setSelectedIndex(0);
        cbxCategoria.setSelectedIndex(0);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            ProdutoDao produtoDao = new ProdutoDao(sessionFactory);

            String sku = txfSKU.getText().trim();
            String nome = txfNome.getText().trim();
            String descricao = txaDescricao.getText();
            String estoque = ftfEstoque.getText();
            String custo = ftfCusto.getText();
            String venda = ftfVenda.getText();
            String desconto = ftfDesconto.getText();
            String status = cbxStatus.getSelectedItem().toString();
            String categoria = "";

            if (sku.isBlank() || nome.isBlank() || descricao.isBlank()
                    || estoque.isBlank() || custo.isBlank()
                    || venda.isBlank() || desconto.isBlank()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
                return;
            }

            if (cbxCategoria.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Selecione uma categoria");
                return;
            } else {
                categoria = cbxCategoria.getSelectedItem().toString();
            }

            if (Double.parseDouble(venda) < Double.parseDouble(custo)) {
                JOptionPane.showMessageDialog(null, "O preço de venda deve ser maior que o preço de custo.");
                return;
            }

            id = produto.getId();
            produto.setSKU(sku);
            produto.setNome(nome);
            produto.setDescricao(descricao);
            produto.setCategoria(categoria);
            produto.setDesconto(Double.parseDouble(desconto));
            produto.setEstoque(Integer.parseInt(estoque));
            produto.setPreco_custo(Double.parseDouble(custo));
            produto.setPreco_venda(Double.parseDouble(venda));
            produto.setStatus(status);

            Optional<Produto> produto0 = Optional.empty();

            if (id == 0) {
                produto0 = produtoDao.salvar(produto);
            } else {
                produto0 = produtoDao.atualizar(produto);
            }

            if (produto0.isPresent()) {
                if (id == 0) {
                    JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!");
                }
            }
        } catch (Exception e) {
            log.error("Erro ao cadastrar produto: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar produto.");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            String busca = txfBusca.getText();

            Object[] cabecalho = {"id", "SKU", "Nome", "Categoria", "Status"};
            Object[][] dadosTabela = new Object[0][5];

            List<Produto> produtos = new ArrayList<>();

            switch (cbxBusca.getSelectedIndex()) {
                case 0: {
                    produtos = new ProdutoDao(sessionFactory).buscarCustomizavel("SKU", busca);
                    break;
                }

                case 1: {
                    produtos = new ProdutoDao(sessionFactory).buscarCustomizavel("nome", busca);
                    break;
                }

                case 2: {
                    produtos = new ProdutoDao(sessionFactory).buscarCustomizavel("categoria", busca);
                    break;
                }

                default:
                    break;
            }

            dadosTabela = new Object[produtos.size()][5];
            if (produtos.size() > 0) {
                for (int i = 0; i < produtos.size(); i++) {
                    dadosTabela[i][0] = produtos.get(i).getId();
                    dadosTabela[i][1] = produtos.get(i).getSKU();
                    dadosTabela[i][2] = produtos.get(i).getNome();
                    dadosTabela[i][3] = produtos.get(i).getCategoria();
                    dadosTabela[i][4] = produtos.get(i).getStatus();
                }
            }

            tblProduto.setModel(new DefaultTableModel(dadosTabela, cabecalho) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            });

            tblProduto.setSelectionMode(0);

            // redimensiona as colunas de uma tabela
            TableColumn column = null;
            for (int i = 0; i < tblProduto.getColumnCount(); i++) {
                column = tblProduto.getColumnModel().getColumn(i);
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                column.setCellRenderer(centerRenderer);
            }

            column = tblProduto.getColumnModel().getColumn(0);
            column.setPreferredWidth(70);
            column.setMaxWidth(70);
            column.setMinWidth(70);
        } catch (Exception e) {
            log.error("Erro ao buscar na tabela de produtos "
                    + "(combobox selected_item: "
                    + cbxBusca.getSelectedItem().toString()
                    + "): " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            String idString = String.valueOf(tblProduto.getValueAt(tblProduto.getSelectedRow(), 0));
            id = Integer.parseInt(idString);
            Optional<Produto> produto0 = new ProdutoDao(sessionFactory).buscar(id);
            produto = produto0.get();

            this.carregarDadosProduto(produto);
        } catch (Exception e) {
            log.error("Erro ao selecionar na tabela de produtos "
                    + "(combobox selected_index: "
                    + cbxBusca.getSelectedIndex()
                    + "): " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao selecionar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed
        private void carregarDadosProduto(Produto produto) {
            txfSKU.setText(produto.getSKU());
            txfNome.setText(produto.getNome());
            txaDescricao.setText(produto.getDescricao());
            ftfEstoque.setText(String.valueOf(produto.getEstoque()));
            ftfCusto.setText(String.valueOf(produto.getPreco_custo()));
            ftfVenda.setText(String.valueOf(produto.getPreco_venda()));
            ftfDesconto.setText(String.valueOf(produto.getDesconto()));

            if (produto.getStatus().equals("Ativo")) {
                cbxStatus.setSelectedIndex(0);
            } else {
                cbxStatus.setSelectedIndex(1);
            }

            String categoria = produto.getCategoria();
            int index = ((DefaultComboBoxModel) cbxCategoria.getModel()).getIndexOf(categoria);
            cbxCategoria.setSelectedIndex(index);

            tbpCadastros.setSelectedIndex(0);
            txfSKU.requestFocus();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundcadastro;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVerProduto;
    private javax.swing.JComboBox<String> cbxBusca;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxStatus;
    private javax.swing.JFormattedTextField ftfCusto;
    private javax.swing.JFormattedTextField ftfDesconto;
    private javax.swing.JFormattedTextField ftfEstoque;
    private javax.swing.JFormattedTextField ftfVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JPanel pnlcadastros;
    private javax.swing.JPanel pnlprodutos;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTabbedPane tbpCadastros;
    private javax.swing.JTextArea txaDescricao;
    private javax.swing.JTextField txfBusca;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfSKU;
    // End of variables declaration//GEN-END:variables
}
