/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author evely
 */
public class DlgPet extends javax.swing.JDialog {

    
    public DlgPet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlcadastropet = new javax.swing.JPanel();
        cbxRaca = new javax.swing.JComboBox<>();
        cbxSexo = new javax.swing.JComboBox<>();
        txfPorte = new javax.swing.JTextField();
        txfNome = new javax.swing.JTextField();
        ftfData = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        cbxStatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlcadastropet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxRaca.setBackground(new java.awt.Color(218, 218, 218));
        cbxRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino" }));
        pnlcadastropet.add(cbxRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 330, 40));

        cbxSexo.setBackground(new java.awt.Color(218, 218, 218));
        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino" }));
        pnlcadastropet.add(cbxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 260, 40));

        txfPorte.setBackground(new java.awt.Color(218, 218, 218));
        txfPorte.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txfPorte.setToolTipText("");
        txfPorte.setBorder(null);
        pnlcadastropet.add(txfPorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 300, 30));

        txfNome.setBackground(new java.awt.Color(218, 218, 218));
        txfNome.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txfNome.setToolTipText("");
        txfNome.setBorder(null);
        pnlcadastropet.add(txfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 300, 30));

        ftfData.setBackground(new java.awt.Color(218, 218, 218));
        ftfData.setToolTipText("");
        pnlcadastropet.add(ftfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 310, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlcadastropet.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 340, 40));

        cbxStatus.setBackground(new java.awt.Color(218, 218, 218));
        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));
        pnlcadastropet.add(cbxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 310, 40));

        jButton1.setBackground(new java.awt.Color(58, 203, 199));
        jButton1.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.setBorder(null);
        pnlcadastropet.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 160, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastropet.png"))); // NOI18N
        pnlcadastropet.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlcadastropet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlcadastropet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> cbxRaca;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxStatus;
    private com.toedter.calendar.JDateChooser ftfData;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel pnlcadastropet;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfPorte;
    // End of variables declaration//GEN-END:variables
}
