/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CaixaDao;
import dao.ProdutoDao;
import dao.VendaDao;
import dao.VendaProdutoDao;
import entities.Caixa;
import entities.Funcionario;
import entities.Produto;
import entities.Venda;
import entities.VendaProduto;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lombok.extern.log4j.Log4j2;
import org.hibernate.SessionFactory;
import utils.HibernateUtil;

@Log4j2
public class DlgVenda extends javax.swing.JDialog {

    private final SessionFactory sessionFactory;
    private Produto produto = new Produto();
    private Map<Produto, Integer> itens = new HashMap<>();
    DefaultTableModel dtmVendas = new DefaultTableModel();
    String preco;
    Funcionario funcionario;
    Venda venda;

    public DlgVenda(java.awt.Frame parent, boolean modal, Funcionario funcionario) {
        super(parent, modal);
        initComponents();
        this.funcionario = funcionario;
        this.sessionFactory = HibernateUtil.getSessionFactory();
        this.venda = new Venda();
    }

    String formapagamento = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlvendas = new javax.swing.JPanel();
        chkCartao = new javax.swing.JCheckBox();
        chkDinheiro = new javax.swing.JCheckBox();
        lblPagar = new javax.swing.JLabel();
        btnfinalizar = new javax.swing.JButton();
        tfdnome = new javax.swing.JTextField();
        tfdCodigo = new javax.swing.JTextField();
        tfdPagar = new javax.swing.JTextField();
        btnadicionar = new javax.swing.JButton();
        btndescartar = new javax.swing.JButton();
        tfdTotal = new javax.swing.JLabel();
        lblFechar = new javax.swing.JLabel();
        lblIdVenda = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaVenda = new javax.swing.JTable();
        btnbuscacodigo = new javax.swing.JButton();
        tfdProduto = new javax.swing.JTextField();
        tfdValorUnitario = new javax.swing.JTextField();
        tfdValorTotal = new javax.swing.JTextField();
        spnQuantidade = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pnlvendas.setBackground(new java.awt.Color(15, 112, 112));
        pnlvendas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkCartao.setBackground(new java.awt.Color(255, 255, 255));
        chkCartao.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        chkCartao.setText("    Cartão");
        chkCartao.setToolTipText("");
        chkCartao.setFocusPainted(false);
        chkCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCartaoActionPerformed(evt);
            }
        });
        pnlvendas.add(chkCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 150, -1, -1));

        chkDinheiro.setBackground(new java.awt.Color(255, 255, 255));
        chkDinheiro.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        chkDinheiro.setText("    Dinheiro");
        chkDinheiro.setToolTipText("");
        chkDinheiro.setFocusPainted(false);
        chkDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDinheiroActionPerformed(evt);
            }
        });
        pnlvendas.add(chkDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, -1, -1));

        lblPagar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblPagar.setText("Pagar:");
        pnlvendas.add(lblPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, -1, -1));

        btnfinalizar.setBackground(new java.awt.Color(2, 166, 166));
        btnfinalizar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btnfinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnfinalizar.setText("Finalizar venda");
        btnfinalizar.setBorder(null);
        btnfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinalizarActionPerformed(evt);
            }
        });
        pnlvendas.add(btnfinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 300, 30));

        tfdnome.setEditable(false);
        tfdnome.setBackground(new java.awt.Color(230, 227, 227));
        tfdnome.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfdnome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfdnome.setBorder(null);
        pnlvendas.add(tfdnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 420, 250, 30));

        tfdCodigo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfdCodigo.setToolTipText("");
        tfdCodigo.setBorder(null);
        pnlvendas.add(tfdCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 60, 30));

        tfdPagar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfdPagar.setToolTipText("");
        tfdPagar.setBorder(null);
        pnlvendas.add(tfdPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, 140, 40));

        btnadicionar.setBackground(new java.awt.Color(255, 255, 255));
        btnadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adicionar.png"))); // NOI18N
        btnadicionar.setBorder(null);
        btnadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarActionPerformed(evt);
            }
        });
        pnlvendas.add(btnadicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 80, 40));

        btndescartar.setBackground(new java.awt.Color(255, 255, 255));
        btndescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descartar.png"))); // NOI18N
        btndescartar.setBorder(null);
        btndescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndescartarActionPerformed(evt);
            }
        });
        pnlvendas.add(btndescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 80, 40));

        tfdTotal.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        tfdTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pnlvendas.add(tfdTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 580, 220, 30));

        lblFechar.setBackground(new java.awt.Color(58, 203, 199));
        lblFechar.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(58, 203, 199));
        lblFechar.setText("X");
        lblFechar.setToolTipText("");
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        pnlvendas.add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 5, -1, -1));

        lblIdVenda.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblIdVenda.setForeground(new java.awt.Color(2, 166, 166));
        lblIdVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlvendas.add(lblIdVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 90, 30));

        tabelaVenda.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        tabelaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Preço", "Quantidade", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaVenda.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaVenda.setRowHeight(35);
        tabelaVenda.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(tabelaVenda);

        pnlvendas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 810, 450));

        btnbuscacodigo.setBackground(new java.awt.Color(2, 166, 166));
        btnbuscacodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pesquisa.png"))); // NOI18N
        btnbuscacodigo.setBorder(null);
        btnbuscacodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscacodigoActionPerformed(evt);
            }
        });
        pnlvendas.add(btnbuscacodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 79, 30, 30));

        tfdProduto.setEditable(false);
        tfdProduto.setBackground(new java.awt.Color(229, 233, 233));
        tfdProduto.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        tfdProduto.setBorder(null);
        pnlvendas.add(tfdProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 380, 30));

        tfdValorUnitario.setBackground(new java.awt.Color(229, 233, 233));
        tfdValorUnitario.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        tfdValorUnitario.setToolTipText("");
        tfdValorUnitario.setBorder(null);
        pnlvendas.add(tfdValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 110, 30));

        tfdValorTotal.setBackground(new java.awt.Color(229, 233, 233));
        tfdValorTotal.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        tfdValorTotal.setToolTipText("");
        tfdValorTotal.setBorder(null);
        pnlvendas.add(tfdValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 110, 30));

        spnQuantidade.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        spnQuantidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        spnQuantidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spnQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantidadeStateChanged(evt);
            }
        });
        pnlvendas.add(spnQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 110, 30));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel2.setText("R$");
        pnlvendas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 155, -1, -1));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel1.setText("R$");
        pnlvendas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 155, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menucomprass.png"))); // NOI18N
        pnlvendas.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlvendas, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlvendas, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarDTM() {

        dtmVendas = (DefaultTableModel) tabelaVenda.getModel();
        dtmVendas.setRowCount(0);

        for (var entry : itens.entrySet()) {
            Produto prodEntry = entry.getKey();
            Integer qtde = entry.getValue();
            dtmVendas.addRow(new Object[]{prodEntry.getId(), prodEntry.getNome(),
                prodEntry.getPreco_venda(), qtde, String.valueOf(prodEntry.getPreco_venda() * qtde)});
        }

    }

    private void chkCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCartaoActionPerformed
        chkDinheiro.setSelected(false);
        tfdPagar.setEditable(true);
        formapagamento = "Cartão";
    }//GEN-LAST:event_chkCartaoActionPerformed

    private void chkDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDinheiroActionPerformed
        if (chkDinheiro.isSelected()) {
            chkCartao.setSelected(false);
            tfdPagar.setEditable(true);
            formapagamento = "Dinheiro";
        }
    }//GEN-LAST:event_chkDinheiroActionPerformed

    private void btnfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinalizarActionPerformed
        int cont = tabelaVenda.getRowCount();
        System.out.println("contagem: " + cont);

        if (cont <= 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Você deve adicionar itens para venda!",
                    "Atencão",
                    JOptionPane.ERROR_MESSAGE);

        } else if (!chkDinheiro.isSelected() && !chkCartao.isSelected()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Você precisa selecionar uma forma de pagamento!",
                    "Atencão",
                    JOptionPane.ERROR_MESSAGE);

        } else if (tfdPagar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Você precisa informar o valor a ser pago!",
                    "Atencão",
                    JOptionPane.ERROR_MESSAGE);

        } else {
            Double valorPagar = Double.parseDouble(tfdPagar.getText().replaceAll(",", "."));
            Double totalc = Double.parseDouble(tfdTotal.getText().replaceAll(",", "."));
            if (valorPagar < totalc) {
                JOptionPane.showMessageDialog(rootPane,
                        "O valor a ser pago está incorreto!",
                        "Atencão",
                        JOptionPane.ERROR_MESSAGE);

            } else {

                VendaDao vendaDao = new VendaDao(sessionFactory);

                Caixa caixa = new Caixa();
                CaixaDao caixaDao = new CaixaDao(sessionFactory);

                Double total = Double.valueOf(tfdTotal.getText().replaceAll(",", ".")).doubleValue();
                LocalDate data = LocalDate.now();

                venda.setData_venda(data);
                venda.setValor_total(total);

//                caixa.setServico(servico);
                caixa.setFuncionario(funcionario);
                caixa.setValor_total(total);
                caixa.setVenda(venda);
                venda.setCaixa(caixa);

                vendaDao.salvar(venda);
                caixaDao.salvar(caixa);

                if (valorPagar > total) {
                    Double troco = (valorPagar - total);
                    JOptionPane.showMessageDialog(rootPane,
                            "Venda concluída com sucesso!\n"
                            + "Troco: R$" + troco,
                            "Venda finalizada", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(rootPane,
                            "Venda concluída com sucesso!",
                            "Venda finalizada", JOptionPane.INFORMATION_MESSAGE);
                }

//                -- --ATUALIZA OS DADOS DO PRODUTO NO BANCO DE DADOS ----------
                ProdutoDao produtoDao = new ProdutoDao(sessionFactory);
                int qtd;
                int retirado;
                int totalProd;

                for (var entry : itens.entrySet()) {
                    Produto prodEntry = entry.getKey();
                    Integer quantidade = entry.getValue();

                    retirado = quantidade;
                    qtd = prodEntry.getEstoque();
                    totalProd = qtd - retirado;

                    prodEntry.setEstoque(totalProd);
                    produtoDao.atualizar(prodEntry);
                }

//                --------------------------------------------------------------
//                -- --CRIA O VENDAPRODUTO NO BANCO DE DADOS RELATIVO A ESTA VENDA ----------
                VendaProdutoDao dao = new VendaProdutoDao(sessionFactory);

                for (var entry : itens.entrySet()) {
                    Produto prodEntry = entry.getKey();
                    Integer quantidade = entry.getValue();

                    VendaProduto item = new VendaProduto();
                    int idUltimaVenda = new VendaDao(sessionFactory).buscarTodos().size();
                    Optional<Venda> p = new VendaDao(sessionFactory).buscar(idUltimaVenda);
                    this.venda = p.get();

                    item.setProduto(prodEntry);
                    item.setVenda(venda);
                    item.setQtde_item(quantidade);
                    item.setValor_item(prodEntry.getPreco_venda());
                    dao.salvar(item);
                }

//                --------------------------------------------------------------
                DefaultTableModel tabela = (DefaultTableModel) tabelaVenda.getModel();
                tabela.setRowCount(0);
                tfdTotal.setText("");
                tfdnome.setText("");
                tfdPagar.setText("0");
                chkDinheiro.setSelected(false);
                chkCartao.setSelected(false);
            }
        }

    }//GEN-LAST:event_btnfinalizarActionPerformed

    private void btnbuscacodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscacodigoActionPerformed
        try {
            int id = Integer.parseInt(tfdCodigo.getText());
            Optional<Produto> p = new ProdutoDao(sessionFactory).buscar(id);
            Produto produto = p.get();
            String venda = priceToString(produto.getPreco_venda());
            tfdValorUnitario.setText(venda);
            tfdValorTotal.setText(venda);
            preco = venda;
            spnQuantidade.setValue(1);
            tfdProduto.setText(produto.getNome());
        } catch (Exception e) {
            log.error("Erro ao buscar produto: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto: código inválido.");
        }
    }//GEN-LAST:event_btnbuscacodigoActionPerformed

    private void spnQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantidadeStateChanged
        int qtd = (Integer) spnQuantidade.getValue();
        double venda = Double.parseDouble(preco.replaceAll(",", "."));
        double total = (qtd * venda);
        String total2 = priceToString(total);
        tfdValorTotal.setText(total2);
    }//GEN-LAST:event_spnQuantidadeStateChanged

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void btnadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarActionPerformed

        int quantidade = (Integer) spnQuantidade.getValue();

        if (tfdCodigo.getText().isEmpty() || tfdCodigo.getText().equals("0")) {
            JOptionPane.showMessageDialog(rootPane,
                    "Você deve inserir o código do produto!",
                    "Atencão",
                    JOptionPane.ERROR_MESSAGE);

        } else if (quantidade == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "A quantidade de itens não pode ser zero!",
                    "Atencão",
                    JOptionPane.ERROR_MESSAGE);

        } else {

            //-----------------------------------------------------------------------------------//
            int verificar;

            int codigo = Integer.parseInt(tfdCodigo.getText());
            Optional<Produto> p = new ProdutoDao(sessionFactory).buscar(codigo);
            Produto produto = p.get();
            verificar = produto.getEstoque();

            if (verificar < quantidade) {
                JOptionPane.showMessageDialog(rootPane,
                        "A quantidade não está disponível em estoque!",
                        "Atencão",
                        JOptionPane.ERROR_MESSAGE);

            } else {
                boolean produtoExiste = false;

                for (var entry : itens.entrySet()) {
                    Produto prodEntry = entry.getKey();
                    Integer qtde = entry.getValue();
                    if (prodEntry.getId() == produto.getId()) {
                        produtoExiste = true;

                        if (verificar < qtde + quantidade) {
                            JOptionPane.showMessageDialog(rootPane,
                                    "A quantidade não está disponível em estoque!",
                                    "Atencão",
                                    JOptionPane.ERROR_MESSAGE);
                        } else {
                            entry.setValue(qtde + quantidade);
                        }
                    }
                }

                if (!produtoExiste) {
                    itens.put(produto, quantidade);
                }

                this.atualizarDTM();

                atualizaSubtotal();
                limparCampos();
            }
        }
    }//GEN-LAST:event_btnadicionarActionPerformed

    public void atualizaSubtotal() {

        double subtotal = 0f;
        //faz cálculo de subtotal da compra
        for (var entry : itens.entrySet()) {
            Produto prodEntry = entry.getKey();
            Integer qtde = entry.getValue();
            subtotal += (double) qtde * prodEntry.getPreco_venda();
        }
        //insere valor subtotal da compra na label
        tfdTotal.setText(String.valueOf(subtotal));
    }

    public void limparCampos() {
        tfdProduto.setText("");
        tfdValorUnitario.setText("0");
        tfdValorTotal.setText("0");
        spnQuantidade.setValue(0);
        tfdCodigo.setText("0");
    }

    private void btndescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndescartarActionPerformed
        if (tabelaVenda.getSelectedRowCount() == 1) {
            String idString = String.valueOf(tabelaVenda.getValueAt(tabelaVenda.getSelectedRow(), 0));
            int idItem = Integer.parseInt(idString);
            Produto produtoRemover = new Produto();

            for (var entry : itens.entrySet()) {
                Produto prodEntry = entry.getKey();

                if (prodEntry.getId() == idItem) {
                    produtoRemover = prodEntry;
                }
            }

            itens.remove(produtoRemover);
            this.atualizarDTM();
            this.atualizaSubtotal();
        } else {
            if (tabelaVenda.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Tabela está vazia.");
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum item selecionado.");
            }
        }
    }//GEN-LAST:event_btndescartarActionPerformed

    public static String priceWithDecimal(Double price) {
        DecimalFormat formatter = new DecimalFormat("###,###,###.00");
        return formatter.format(price);
    }

    public static String priceWithoutDecimal(Double price) {
        DecimalFormat formatter = new DecimalFormat("###,###,###.##");
        return formatter.format(price);
    }

    public static String priceToString(Double price) {
        String toShow = priceWithoutDecimal(price);
        if (toShow.indexOf(".") > 0) {
            return priceWithDecimal(price);
        } else {
            return priceWithoutDecimal(price);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadicionar;
    private javax.swing.JButton btnbuscacodigo;
    private javax.swing.JButton btndescartar;
    private javax.swing.JButton btnfinalizar;
    private javax.swing.JCheckBox chkCartao;
    private javax.swing.JCheckBox chkDinheiro;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblIdVenda;
    private javax.swing.JLabel lblPagar;
    private javax.swing.JPanel pnlvendas;
    private javax.swing.JSpinner spnQuantidade;
    private javax.swing.JTable tabelaVenda;
    private javax.swing.JTextField tfdCodigo;
    private javax.swing.JTextField tfdPagar;
    private javax.swing.JTextField tfdProduto;
    private javax.swing.JLabel tfdTotal;
    private javax.swing.JTextField tfdValorTotal;
    private javax.swing.JTextField tfdValorUnitario;
    private javax.swing.JTextField tfdnome;
    // End of variables declaration//GEN-END:variables
}
